# Generated by Django 3.0.4 on 2020-03-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_family', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_elements', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FabricBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_brand', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedUses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FabricCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_released', models.IntegerField(blank=True)),
                ('brand', models.ManyToManyField(to='fabric.FabricBrand')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_family', models.ManyToManyField(to='fabric.ColorFamily')),
                ('design_elements', models.ManyToManyField(blank=True, to='fabric.DesignElements')),
                ('designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fabric.Designer')),
                ('fabric_collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fabric.FabricCollection')),
                ('fabric_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fabric.FabricType')),
                ('image', models.ManyToManyField(blank=True, to='upload_images.UploadImage')),
                ('recommended_uses', models.ManyToManyField(blank=True, to='fabric.RecommendedUses')),
            ],
        ),
        migrations.AddField(
            model_name='designer',
            name='designs_for',
            field=models.ManyToManyField(to='fabric.FabricBrand'),
        ),
        migrations.AddField(
            model_name='designer',
            name='fabric_collections',
            field=models.ManyToManyField(blank=True, to='fabric.FabricCollection'),
        ),
    ]
