# Generated by Django 3.0.4 on 2020-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriccollection',
            name='collection',
            field=models.CharField(default='Collection', max_length=100),
            preserve_default=False,
        ),
    ]
