# Generated by Django 3.0.4 on 2020-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternview',
            name='view',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
