# Generated by Django 3.0.4 on 2020-03-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload_images', '0001_initial'),
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('images', models.ManyToManyField(blank=True, to='upload_images.UploadImage')),
            ],
        ),
        migrations.CreateModel(
            name='PatternCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatternView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=100)),
                ('notions', models.TextField()),
                ('fabric_recommendation', models.ManyToManyField(to='fabric.FabricType')),
                ('pattern_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.Pattern')),
                ('pattern_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.PatternType')),
            ],
        ),
        migrations.CreateModel(
            name='PatternDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('designs_for', models.ManyToManyField(blank=True, to='patterns.PatternCompany')),
                ('pattern_collections', models.ManyToManyField(blank=True, to='patterns.PatternCollection')),
            ],
        ),
        migrations.AddField(
            model_name='patterncollection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.PatternCompany'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patterns.PatternCollection'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.PatternCompany'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_designer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patterns.PatternDesigner'),
        ),
    ]
